# render.yaml
services:
  - type: web
    name: cryptosecure-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: bash backend/start.sh
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
    autoDeploy: true
    region: oregon
    buildFilter:
      paths:
        - backend/**

  - type: static
    name: crypto-secure-frontend
    env: static
    plan: free
    buildCommand: npm install && npm run build
    staticPublishPath: frontend/dist
    buildFilter:
      paths:
        - frontend/**

